language: java
dist: trusty
sudo: required

addons:
  sonarqube:
    organization: "alphau"


services:
- mongodb
- docker
script:
- sonar-scanner -X
- mvn clean install docker:build
jdk:
- oraclejdk8