language: java
dist: trusty
sudo: true
addons:
  sonarqube:
    token:
      secure: R+3WhCY99byWt5ZQeeZbzXr9pf40w0HpfLmphWwLtAofkbtJYw/JczRJqgF72OA8NzW+UDNXAM0tCIe+fl84f5G/+36UxnsSOjekqhKYU7rwHZeBao0x9v1Vpk/NEUsee5QDS9v9X3AIZop5wEeDDhIoFz5Ub9qnyjVmN/viFmIM3Qkx6BrusRxEeNXsjOYIU/coqmdv6aqv0FbGOAFWREMxaXftwS26qqMNwG3o/24hGJrRrynPtIvRE/zyoEdS4ZL16KwYJpeRa3UKbGEqFDiVn9vjwK+tFXbRKHSgdx+YIUswR36Iv7DVH+0MhGfXhycVdNpo/igud67SMdUf+MzPBM09Ige++nNNbyp3CDcsrcgsq7BYfEeSg8rTs31J9Tr4eNisTr97Wi5Mfx9Tyg/f0lSxxdqflEOBh9GZvWimNncqbzP80QMGVJyGcGJwOLLMEbWs7cj9HM8AzCs2APoM2pIOw66noKkYvtoH4erEIaKSOKLG4/4Z/IJESfPXDV6W1a+J4HFj/pVsP2sh/rNEarFAsDsSY1fP0gl7wFVwsuYECZhpBtgm/c67kCrWUl0EvQuTm6mINpEXqjYI3sIJnbNK3l43MusBOWcZcfHIJ/6L8dTF/HG+9nKcAv4qCL/GpGIcEAyv6pe+LpmZu9dZ+XbUNXqzv2wvtxlCfNw=
services:
- mongodb
- docker
script:
- mvn clean install docker:build
- sonar-scanner
jdk:
- oraclejdk8
