language: java
dist: trusty
sudo: required
addons:
  sonarqube:
    token:
      secure: "UxyWPg+EEjpqnCf9oKWY6i6N61mESS88R6tjO0ELniLkuz75UdPKvtkRpZu2YcjixoluHUIm7hwfpeZyN/RR3bkshUjLxhu+mc9UoFhkZAfB3EVmvDmrG6A0ryB488YtwXq8Fxr8eYjcPLoN/Pj8h9Uv636BDU7Z61f25gEJjarKpqPpqenFu+phzUIOruyPOLiMWArdJ4sslYoAfUEDISW5AQ137VLmIymEnp3iTKPRtS5HajeCgBsjZbC4WVeA8sI3d9TH0n+y9tQkRp/PZsXEswptXyFP9cKvO0AOsmnsaOOGhwHRnso3nJvZmn18J5Zj9DLUiVKZjYkoA8IwFkbK8mx7TDgdU7Nk95KAr61EfeX4x1Wgp3iZNOAHASROnjfLuzeEEofZNXiVUNvxu54gSPWrvhrnuYUFe1S3V5v3NC+Y74fugwI2f1nBJ673eYKXQszfYR4x/VMmmxG/ozGJ6EN+xIN43PtVD0eCEpMnHSy0DE1bcQSJPmsi1eXMS8cSQYcIGxSGef6SEyJuM5ej3jSc3dYUkUasJSmLOqIhhOlbNRwQtfjPsGMgrHassuXExrwzq2z/aLSMn4TKybPhEnYXNUgMjfHx2slOotdaUrDmwn5nOjeGb+RshzElwHfJdHLDk9H7m1wxS5JO7S54eRmeY9AjVYtyQMgsstk="
services:
- mongodb
- docker
script:
- sonar-scanner -X
- mvn clean install docker:build

jdk:
- oraclejdk8
